export const WORKERS = [
  {
    id: 1,
    name: 'Ramesh Kumar',
    avatar: 'R',
    skills: ['Painter', 'Mason'],
    area: 'Sector 29, Gurugram',
    rate: 500,
    rating: 4.9,
    reviews: 38,
    jobsDone: 38,
    isOnline: true,
    experience: '6 years',
    bio: 'Expert in interior and exterior painting. I use quality materials and finish on time. Available 7 days a week.',
    badge: 'Top Rated',
    responseTime: '~10 min',
  },
  {
    id: 2,
    name: 'Suresh Yadav',
    avatar: 'S',
    skills: ['Carpenter', 'Painter'],
    area: 'DLF Phase 2, Gurugram',
    rate: 450,
    rating: 4.7,
    reviews: 24,
    jobsDone: 24,
    isOnline: true,
    experience: '4 years',
    bio: 'Skilled carpenter for furniture repair, wardrobes, and custom woodwork. Also do painting when needed.',
    badge: null,
    responseTime: '~20 min',
  },
  {
    id: 3,
    name: 'Mohan Lal',
    avatar: 'M',
    skills: ['Plumber', 'AC Repair'],
    area: 'Sushant Lok, Gurugram',
    rate: 600,
    rating: 4.8,
    reviews: 51,
    jobsDone: 51,
    isOnline: false,
    experience: '8 years',
    bio: 'Senior plumber with expertise in pipe fitting, leak repair, and bathroom installation. Also certified for AC servicing.',
    badge: 'Top Rated',
    responseTime: '~30 min',
  },
  {
    id: 4,
    name: 'Deepak Singh',
    avatar: 'D',
    skills: ['Electrician'],
    area: 'Palam Vihar, Gurugram',
    rate: 550,
    rating: 4.6,
    reviews: 17,
    jobsDone: 17,
    isOnline: true,
    experience: '5 years',
    bio: 'Licensed electrician for wiring, switches, fans, and panel work. Safety-first approach on every job.',
    badge: null,
    responseTime: '~15 min',
  },
  {
    id: 5,
    name: 'Ganesh Nair',
    avatar: 'G',
    skills: ['Gardener'],
    area: 'Sector 14, Gurugram',
    rate: 350,
    rating: 5.0,
    reviews: 12,
    jobsDone: 12,
    isOnline: true,
    experience: '3 years',
    bio: 'Passionate gardener for trimming, planting, and landscape work. Your garden will look its best.',
    badge: 'New & Rising',
    responseTime: '~5 min',
  },
  {
    id: 6,
    name: 'Vijay Chauhan',
    avatar: 'V',
    skills: ['Driver'],
    area: 'MG Road, Gurugram',
    rate: 400,
    rating: 4.5,
    reviews: 29,
    jobsDone: 29,
    isOnline: false,
    experience: '7 years',
    bio: 'Experienced driver for daily commutes, airport drops, outstation trips. Owns a clean Maruti Ertiga.',
    badge: null,
    responseTime: '~25 min',
  },
  {
    id: 7,
    name: 'Arjun Mehta',
    avatar: 'A',
    skills: ['Welder', 'Mason'],
    area: 'Sector 56, Gurugram',
    rate: 650,
    rating: 4.8,
    reviews: 20,
    jobsDone: 20,
    isOnline: true,
    experience: '9 years',
    bio: 'Professional welder and masonry expert. Gate work, grills, wall repair — I handle it all with precision.',
    badge: null,
    responseTime: '~20 min',
  },
  {
    id: 8,
    name: 'Pradeep Cook',
    avatar: 'P',
    skills: ['Cook'],
    area: 'Cyber City, Gurugram',
    rate: 500,
    rating: 4.7,
    reviews: 15,
    jobsDone: 15,
    isOnline: true,
    experience: '10 years',
    bio: 'Home cook specializing in North Indian, South Indian, and Chinese cuisine. Perfect for events and daily cooking.',
    badge: null,
    responseTime: '~10 min',
  },
]

export const ALL_SKILLS = [
  'All', 'Painter', 'Carpenter', 'Plumber', 'Electrician',
  'Gardener', 'Driver', 'Sweeper', 'Mason', 'Welder', 'AC Repair', 'Cook',
]